CREATE TABLE USER_INFO (
	id serial PRIMARY KEY,
	NAME VARCHAR ( 250 )  NULL,
	SURNAME VARCHAR ( 250 )  NULL,
	BIRTHDAY DATE  NULL,
	PASSWORD VARCHAR ( 250 )  NULL,
	EMAIL VARCHAR ( 250 )  NULL	
);